Website/Website/urls.py
from django.contrib import admin
from django.urls import path, include
from simple_page import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('simple_page/', include('simple_page.urls'))
]

Website/simple_page/urls.py
from django.urls import path
from . import views

app_name = 'simple_page'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('register', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout')
]

Website/simple_page/models.py
from django.db import models

# Create your models here.

Website/simple_page/forms.py
from django import forms
from django.contrib.auth.models import User

class User_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

        

Website/simple_page/views.py
from django.shortcuts import render

from simple_page.forms import User_Form

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'simple_page/index.html')

def about_us(request):
    return render(request, 'simple_page/about_us.html')

def register(request):
    
    registered = False

    if request.method == 'POST':
        user_form = User_Form(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True

        else:
            print(user_form.errors)

    else:
        user_form = User_Form()

    return render(request, 'simple_page/registration.html', {
                            'user_form':user_form,
                            'registered':registered
                            })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
    
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')

        else:
            print("Some tried tol ogin failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, 'simple_page/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

Website/templates/simple_page/about_us.html
{% extends 'simple_page/base.html' %} {% block body_block %} {% lorem 9 b random
%} {% endblock body_block %}

Website/templates/simple_page/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" />
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <title>Bootstrap</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
      <a href="{% url 'simple_page:index' %}" class="navbar-brand pt-4">
        <h1 class=""><span class="bg-danger">S</span>imple Page</h1>
        <figcaption class="blockquote-footer pt-2">
          for <cite title="Source Title">Simple Companies</cite>
        </figcaption>
      </a>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href=" {% url 'simple_page:about_us' %}" class="nav-link">O nas<span
                class="border border-danger border-end"></span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'simple_page:user_logout' %}" class="nav-link">Wyloguj się<span
                class="border border-danger border-end"></span></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="#" class="nav-link">Rejestracja<span class="border border-danger border-end"></span></a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">Zaloguj się<span class="border border-danger border-end"></span></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block body_block %} {% endblock body_block %}

  <!-- Remove the container if you want to extend the Footer to full width. -->
  <div class="container-fluid my-5">
    <footer class="bg-dark text-center text-white">
      <!-- Grid container -->
      <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-facebook"></i></a>

          <!-- Twitter -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-twitter"></i></a>

          <!-- Google -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-google"></i></a>

          <!-- Instagram -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-instagram"></i></a>

          <!-- Linkedin -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-linkedin"></i></a>

          <!-- Github -->
          <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-github"></i></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2022 Copyright:
        <a class="text-white" href="#">Marcin Krawczyk</a>
      </div>
      <!-- Copyright -->
    </footer>
  </div>
  <!-- End of .container -->
</body>

</html>

Website/templates/simple_page/index.html
{% extends 'simple_page/base.html' %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">WELCOME USER!!! YOU ARE LOGIN NOW!!</h1>
  </div>
</div>
{% else %}

<div class="container pt-4 py-5 my-auto">
  <div class="row">
    <div class="col-md-4 d-flex justify-content-center">
      <div class="card bg-secondary text-light">
        <div class="cards-body text-center my-auto">
          <div class="h3 p-3">
            <i class="bi bi-1-square"></i>
          </div>
          <h5 class="card-title lead">Rejestracja</h5>
          <p class="card-text small p-3">
            Aby zacząć korzystać z serwisu, musisz się wcześniej zalogować.
            Jeżeli nie masz konta. Zarejestruj się!
          </p>
          <a href="{% url 'simple_page:register' %}" class="btn btn-sm btn-danger">Zarejestruj się</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 d-flex justify-content-center">
      <div class="card bg-dark text-light">
        <div class="cards-body text-center my-auto">
          <div class="h3 p-3">
            <i class="bi bi-2-square"></i>
          </div>
          <h5 class="card-title lead">Logowanie</h5>
          <p class="card-text small p-3">
            Aby zacząć korzystać z serwisu, musisz się wcześniej zalogować.
            Jeżeli nie masz konta. Zarejestruj się!
          </p>
          <a href="{% url 'simple_page:user_login' %}" class="btn btn-sm btn-danger">Zaloguj się</a>
        </div>
      </div>
    </div>

    <div class="col-md-4 d-flex justify-content-center">
      <div class="card bg-secondary text-light">
        <div class="cards-body text-center my-auto">
          <div class="h3 p-3">
            <i class="bi bi-3-square bg-"></i>
          </div>
          <h5 class="card-title lead">O Nas!</h5>
          <p class="card-text small p-3">
            Aby zacząć korzystać z serwisu, musisz się wcześniej zalogować.
            Jeżeli nie masz konta. Zarejestruj się!
          </p>
          <a href="{% url 'simple_page:about_us' %}" class="btn btn-sm btn-danger">Poznaj nas</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endif %} {% endblock body_block %}

Website/templates/simple_page/login.html
{% extends 'simple_page/base.html' %} {% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'simple_page:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username" />

    <label for="password">Username:</label>
    <input type="password" name="password" />

    <input type="submit" value="Login" />
  </form>
</div>

{% endblock body_block %}

Website/templates/simple_page/registration.html
{% extends 'simple_page/base.html' %} {% load static %} {% block body_block %}

<div class="container d-flex justify-content-center">
  <div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %} {{ user_form.as_p }}
      <input type="submit" value="Register" />
    </form>

    {% endif %}
  </div>
</div>
{% endblock %}

Website/templates/simple_page/temp.html
<div class="container">
  <div class="card bg-light">
    <article class="card-body" style="">
      <h4 class="card-title mt-3 text-center">Create Account</h4>
      <p class="text-center">Get started with your free account</p>
      <form>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
          </div>
          <input
            name=""
            class="form-control"
            placeholder="Full name"
            type="text"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-envelope"></i>
            </span>
          </div>
          <input
            name=""
            class="form-control"
            placeholder="Email address"
            type="email"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
          </div>
          <input
            name=""
            class="form-control"
            placeholder="Phone number"
            type="text"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text">
              <i class="fa fa-building"></i>
            </span>
          </div>
          <select class="form-control">
            <option selected="">Select job type</option>
            <option>Designer</option>
            <option>Manager</option>
            <option>Accaunting</option>
          </select>
        </div>
        <!-- form-group end.// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <input
            class="form-control"
            placeholder="Create password"
            type="password"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
          </div>
          <input
            class="form-control"
            placeholder="Repeat password"
            type="password"
          />
        </div>
        <!-- form-group// -->
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">
            Create Account
          </button>
        </div>
        <!-- form-group// -->
        <p class="text-center">Have an account? <a href="">Log In</a></p>
      </form>
    </article>
  </div>
  <!-- card.// -->
</div>
<!--container end.//-->